attempt to update to 1.21.5
> Task :1.21.5:compileKotlin FAILED
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/commands/LeaderboardCommand.kt:76:57 Argument type mismatch: actual type is 'net.minecraft.text.HoverEvent.Action', but 'kotlin.Function0<net.minecraft.text.HoverEvent.Action!>' was expected.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/commands/LeaderboardCommand.kt:76:86 Too many arguments for 'public final fun net/minecraft/text/HoverEvent(function: () -> net/minecraft/text/HoverEvent.Action!): net/minecraft/text/HoverEvent'.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/commands/LeaderboardCommand.kt:77:60 Argument type mismatch: actual type is 'net.minecraft.text.ClickEvent.Action', but 'kotlin.Function0<net.minecraft.text.ClickEvent.Action!>' was expected.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/commands/LeaderboardCommand.kt:77:91 Too many arguments for 'public final fun net/minecraft/text/ClickEvent(function: () -> net/minecraft/text/ClickEvent.Action!): net/minecraft/text/ClickEvent'.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/commands/LeaderboardCommand.kt:93:33 Argument type mismatch: actual type is 'net.minecraft.text.HoverEvent.Action', but 'kotlin.Function0<net.minecraft.text.HoverEvent.Action!>' was expected.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/commands/LeaderboardCommand.kt:93:62 Too many arguments for 'public final fun net/minecraft/text/HoverEvent(function: () -> net/minecraft/text/HoverEvent.Action!): net/minecraft/text/HoverEvent'.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/commands/LeaderboardCommand.kt:94:33 Argument type mismatch: actual type is 'net.minecraft.text.ClickEvent.Action', but 'kotlin.Function0<net.minecraft.text.ClickEvent.Action!>' was expected.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/commands/LeaderboardCommand.kt:94:68 Too many arguments for 'public final fun net/minecraft/text/ClickEvent(function: () -> net/minecraft/text/ClickEvent.Action!): net/minecraft/text/ClickEvent'.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/commands/ShareCommand.kt:54:37 Argument type mismatch: actual type is 'net.minecraft.text.HoverEvent.Action', but 'kotlin.Function0<net.minecraft.text.HoverEvent.Action!>' was expected.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/commands/ShareCommand.kt:54:66 Too many arguments for 'public final fun net/minecraft/text/HoverEvent(function: () -> net/minecraft/text/HoverEvent.Action!): net/minecraft/text/HoverEvent'.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/format/Components.kt:14:33 Argument type mismatch: actual type is 'net.minecraft.text.HoverEvent.Action', but 'kotlin.Function0<net.minecraft.text.HoverEvent.Action!>' was expected.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/format/Components.kt:14:62 Too many arguments for 'public final fun net/minecraft/text/HoverEvent(function: () -> net/minecraft/text/HoverEvent.Action!): net/minecraft/text/HoverEvent'.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/format/Components.kt:15:33 Argument type mismatch: actual type is 'net.minecraft.text.ClickEvent.Action', but 'kotlin.Function0<net.minecraft.text.ClickEvent.Action!>' was expected.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/format/Components.kt:15:64 Too many arguments for 'public final fun net/minecraft/text/ClickEvent(function: () -> net/minecraft/text/ClickEvent.Action!): net/minecraft/text/ClickEvent'.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/format/Components.kt:25:41 Argument type mismatch: actual type is 'net.minecraft.text.HoverEvent.Action', but 'kotlin.Function0<net.minecraft.text.HoverEvent.Action!>' was expected.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/format/Components.kt:25:70 Too many arguments for 'public final fun net/minecraft/text/HoverEvent(function: () -> net/minecraft/text/HoverEvent.Action!): net/minecraft/text/HoverEvent'.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/format/Components.kt:26:41 Argument type mismatch: actual type is 'net.minecraft.text.ClickEvent.Action', but 'kotlin.Function0<net.minecraft.text.ClickEvent.Action!>' was expected.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/format/Components.kt:26:72 Too many arguments for 'public final fun net/minecraft/text/ClickEvent(function: () -> net/minecraft/text/ClickEvent.Action!): net/minecraft/text/ClickEvent'.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/format/format.kt:27:33 Argument type mismatch: actual type is 'net.minecraft.text.HoverEvent.Action', but 'kotlin.Function0<net.minecraft.text.HoverEvent.Action!>' was expected.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/format/format.kt:27:62 Too many arguments for 'public final fun net/minecraft/text/HoverEvent(function: () -> net/minecraft/text/HoverEvent.Action!): net/minecraft/text/HoverEvent'.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/format/format.kt:40:33 Argument type mismatch: actual type is 'net.minecraft.text.HoverEvent.Action', but 'kotlin.Function0<net.minecraft.text.HoverEvent.Action!>' was expected.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/format/format.kt:40:62 Too many arguments for 'public final fun net/minecraft/text/HoverEvent(function: () -> net/minecraft/text/HoverEvent.Action!): net/minecraft/text/HoverEvent'.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/format/format.kt:48:33 Argument type mismatch: actual type is 'net.minecraft.text.HoverEvent.Action', but 'kotlin.Function0<net.minecraft.text.HoverEvent.Action!>' was expected.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/format/format.kt:48:62 Too many arguments for 'public final fun net/minecraft/text/HoverEvent(function: () -> net/minecraft/text/HoverEvent.Action!): net/minecraft/text/HoverEvent'.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/util/MinecraftStatSource.kt:38:37 Argument type mismatch: actual type is 'net.minecraft.text.HoverEvent.Action', but 'kotlin.Function0<net.minecraft.text.HoverEvent.Action!>' was expected.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/util/MinecraftStatSource.kt:38:66 Too many arguments for 'public final fun net/minecraft/text/HoverEvent(function: () -> net/minecraft/text/HoverEvent.Action!): net/minecraft/text/HoverEvent'.
e: file:///D:/E_Work/AlgoProg/GithubRepo/PlayerStatistics/src/main/kotlin/io/github/kr8gz/playerstatistics/util/MinecraftStatSource.kt:38:77 Unresolved reference 'ItemStackContent'.

author, please help me update this to latest, my server needs it 😭